### ISSUE TITLE
rcf's ODS

### ISSUE THREAD

**Issue by CangHaiQingYue** [zeakey/hed#10]
Thanks for sharing your work.
I saw that you had implemented the rcf net, what is the ODS of this implemention?
Look forward to your！

**Comment by zeakey** [comment]
I didn't check the performance of RCF, but I think it's easy for you to do it yourself.

**Comment by CangHaiQingYue** [comment]
OK, with your help in anther issue, I will be free to run the code.
Thanks!

**Comment by quanlzheng** [comment]
Thanks for your implementation of RCF. The problem for me is the output has no edges using the pretrained model. I don't know why...
