### ISSUE TITLE
when i want to download the pretrained model it told me 403 forbidden

### ISSUE THREAD

**Issue by ZhouKuai2019** [zeakey/hed#16]
the address is data.kaiz.xyz/edges/my_hed_pretrained_bsds.caffemodel
403 Forbidden

    Code: AccessDenied
    Message: Access Denied
    RequestId: 088A3B04BDB1BF5E
    HostId: 2pp+AnL3hyJvPcFdTeL3Wp845kqKlM1KrfUhI3hA81VhsFg80ehIdEuInWQVf9jzPJMqXeUzOaU=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: AccessDenied
    Message: Access Denied

**Comment by zeakey** [comment]
The hyper-link is alive now.

**Comment by ZhouKuai2019** [comment]
Thank you very much but excuse me，i have new error in third step and issued in github




    


On 05/23/2019 09:51, KAI ZHAO wrote: Closed #16.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zeakey/hed/issues/16?email_source=notifications\u0026email_token=AMDVYTFUJF74UCAL33YKNJDPWX2EDA5CNFSM4HOHPHS2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGORS5JFOY#event-2361037499",
"url": "https://github.com/zeakey/hed/issues/16?email_source=notifications\u0026email_token=AMDVYTFUJF74UCAL33YKNJDPWX2EDA5CNFSM4HOHPHS2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGORS5JFOY#event-2361037499",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
