### ISSUE TITLE
error in testing

### ISSUE THREAD

**Issue by ZhouKuai2019** [zeakey/hed#17]
First and second steps are successful.

error in the third

zhoukuai@zhoukuai-B360M-D3V:~/下载/hed-master$ python forward_all()
bash: 未预期的符号 `(' 附近有语法错误
zhoukuai@zhoukuai-B360M-D3V:~/下载/hed-master$ python forward_all.py()
bash: 未预期的符号 `(' 附近有语法错误
zhoukuai@zhoukuai-B360M-D3V:~/下载/hed-master$ python forward_all.py
Traceback (most recent call last):
  File "forward_all.py", line 25, in <module>
    assert isfile(args.model) and isfile(args.net), 'file not exists'
AssertionError: file not exists

**Comment by ZhouKuai2019** [comment]
Hello, Can I beg you for a hint? I tried everything, and it's still the same

**Comment by zeakey** [comment]
Please DO NOT post such uninformative problems here. You should learn to debug your self.
The error information has told you everything.

Again, please DO NOT post such issue.
