### ISSUE TITLE
error == cudaSuccess (2 vs. 0)  out of memory on net.forward()

### ISSUE THREAD

**Issue by rribani** [zeakey/hed#2]
Hi,

I'm facing this issue when trying to run inference on latest caffe version:

syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

It works for me on HED customized version (https://github.com/s9xie/hed).

I'm using Cuda 9.0. Any ideas?

Thanks,
Ricardo

**Comment by zeakey** [comment]
@rribani What's the GPUs are you using? Do you opt on `CUDNN`?

Turning on CUDNN will decrease the GPU memory using.

**Comment by rribani** [comment]
I'm using NVIDIA Quadro K2100M with CUDNN enabled. I'll try to disable CUDNN. Thanks.

**Comment by rribani** [comment]
I figured out that restarting my machine and keeping everything closed, resolved the problem. May it's an issue on the old version of caffe that you're using. Thanks for the help.
