### ISSUE TITLE
Files in readme are not longer available

### ISSUE THREAD

**Issue by heberuriegas** [zeakey/hed#21]
Hi @zeakey, seems like the s3 bucket where the file are allocated is not longer available for download. Can you re-upload again?, or send me the files to heber.fernando@gmail.com, I'll happy to help uploading the files again to a s3 bucket and restore the links. 

I'm trying to understand how it works and the files are important in the process.

The uploading files in the readme are:
- The initial model
- The pretrained model
- Original pretrained model, bsds results and evaluation results
- My Hed pretrained model, bsds results and evaluation results
- The original result image 3063.png
- The my hed result image 3063.png

**Comment by zeakey** [comment]
I'm sorry that the S3 bucket has been deleted by mistake. The only thing I can give you is the initial model <http://data.kaizhao.net/projects/edge/vgg16convs.caffemodel>.

For other files you can eigher train the model and inference on BSDS dataset, or download from the original HED repo.
