### ISSUE TITLE
Error running models/hed.py

### ISSUE THREAD

**Issue by saiaman** [zeakey/hed#3]
>>> python model/hed.py
Traceback (most recent call last):
  File "model/hed.py", line 3, in <module>
    import caffe
  File "caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dynamic module does not define module export function (PyInit__caffe)

build.sh has been run and built .so successfully

**Comment by zeakey** [comment]
Similar problems has been described in <https://github.com/BVLC/caffe/issues/6054>.
