### ISSUE TITLE
The label must be converted to [0,1]？

### ISSUE THREAD

**Issue by xjock** [zeakey/hed#5]
if (target[i] == 1) {
      loss_pos -= input_data[i] * (target[i] - (input_data[i] >= 0)) -
          log(1 + exp(input_data[i] - 2 * input_data[i] * (input_data[i] >= 0)));
      count_[1]++;
    } else if (target[i] == 0) {
      loss_neg -= input_data[i] * (target[i] - (input_data[i] >= 0)) -
          log(1 + exp(input_data[i] - 2 * input_data[i] * (input_data[i] >= 0)));
      count_[0]++;
    } else {
      LOG(FATAL)<<"Unknown target value: " << target[i];
    }

**Comment by zeakey** [comment]
Of course it is. Since the edge detection is indeed a binary classification task where each pixel has to be classified as edge or background.

**Comment by xjock** [comment]
Thanks！
