### ISSUE TITLE
Why do the forward_gpu function call the forward_cpu function and return in balance_cross_entropy_loss_layer.cu?

### ISSUE THREAD

**Issue by xjock** [zeakey/hed#6]
Can I commented out the following code?

Forward_cpu(bottom, top); return;

template <typename Dtype>
void BalanceCrossEntropyLossLayer<Dtype>::Forward_gpu(
    const vector<Blob<Dtype>*>& bottom, const vector<Blob<Dtype>*>& top) {

  Forward_cpu(bottom, top); return;

  // The forward pass computes the sigmoid outputs.
  sigmoid_bottom_vec_[0] = bottom[0];
  sigmoid_layer_->Forward(sigmoid_bottom_vec_, sigmoid_top_vec_);

**Comment by zeakey** [comment]
No, you shouldn't!
I only implemented the CPU part of `BalanceCrossEntropyLoss` and the cuda codes are copied from that of `SigmoidCrossEntropyLoss`.
So `Forward_cpu` is called in the `Forward_gpu` function. 

This is closely related to the warning in #11 .

**Comment by xjock** [comment]
Oh, thank you very much!
