### ISSUE TITLE
Failed in train.py

### ISSUE THREAD

**Issue by huihuangzhao** [zeakey/hed#8]
Hi , i got a error in the train.

F0731 17:12:15.323357 32193 cudnn.hpp:128] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM

Could you please tell me how to solve it? Mann thanks

**Comment by xjock** [comment]
More details?

**Comment by huihuangzhao** [comment]
it seems because i used cudn7.0. Thanks
